### ISSUE TITLE
Connect to solr on startup with command line arg

### ISSUE THREAD

**Issue by claytron** [moliware/solr_cli#8]
I would like to be able to connect directly to Solr when starting up the `solr_cli`.

```
$ solr_cli http://localhost:8983/solr
(http://localhost:8983/solr)$ 
```

This would allow me to quickly bring up the prompt from my command line history or from a program like teamocil that initiates the connection for me.

**Comment by moliware** [comment]
Hi @claytron , that change is already in the master branch. In any case, I'm taking up again this repo and RedTuna/mysolr. I hope that soon I can release a new version :)
